### ISSUE TITLE
library.db stored in /var/lib/mopidy instead of "data_dir" path

### ISSUE THREAD

**Issue by oliverjkb** [mopidy/mopidy-local-sqlite#76]
I have just today installed mopidy on a new server, using the same mopidy.conf template that I always use. 
I copied one file to the media_dir, scanned it, and then wanted to play it with mopidy-musicbox-webclient, but the file didn't show up. On command line I entered the path to the media directory of my config file, but the "sqlite" folder was missing. 
I then did "mopidyctl local scan", which went just fine, stating that the media was found, nothing had to be changed in the Database. 
However, library.db could not be found in the data directory. 
`locate library.db` showed `/var/lib/mopidy/.local/share/mopidy/local-sqlite/library.db` as the libary location. 
So it is written to that path, but mopidy tries to read it from the data_dir. 
I was able to reproduce the error on two systems, all of which are running on Ubuntu 14.04. LTS, installation from repositories, not pip. 
local-sqlite was installed from repositories and from pip (one machine), showing same behavior.
Mopidy Version 1.1.1

**Comment by tkem** [comment]
Starting with v1.0.0, mopidy-local-sqlite uses the new standard extension directory scheme, which does not use the old "local" subdirectory any more. Any existing `library.db` should have been moved to the new directory when upgrading mopidy-local-sqlite, and the extension should read the database file from the new location.
Anything in the logs that hints at why your files can't be found?

**Comment by jodal** [comment]
> locate library.db showed /var/lib/mopidy/.local/share/mopidy/local-sqlite/library.db as the libary location. 

Note that `locate` searches using an index that usually is updated once every 24h. To get up-to-date search results, use `find /usr/lib/mopidy -name library.db`.

**Comment by tkem** [comment]
Re-reading this, `/var/lib/mopidy/.local` seems odd. Did you install mopidy from the apt archive? Did you run `mopidyctl` using `sudo`?

**Comment by jodal** [comment]
Up until Mopidy 1.1.1 `$XDG_DATA_DIR` ended up begin`/var/lib/mopidy/.local/share/mopidy` if it wasn't set in your environment and `/var/lib/mopidy` was your home dir, like it is for the `mopidy` user created by the Debian and Arch package.

**Comment by tkem** [comment]
Closing this due to prolonged inactivity.
