### ISSUE TITLE
[Question] MusicBrainz MBID

### ISSUE THREAD

**Issue by jaedb** [mopidy/mopidy-local-sqlite#81]
I'm building a web client for Mopidy [Spotmop](https://github.com/jaedb/spotmop) but am having trouble implementing user-friendly browsing of local files.

The challenge currently is finding a way to manage the relationships between artists, tracks and albums. The perfect outcome would be to display artists and albums like the rest of the interface (with supporting artwork, ratings, etc). I thought I could achieve this by using the MBID.

However, I can't seem get the MBID from the local database. How do I do this? I've already enabled both `use_artist_mbid_uri` and `use_album_mbid_uri` switches. I've tried reverse-hashing the uri (ie `94800574623098170cd93f3d578eb979`) with no luck.

I get the feeling I'm missing something really obvious...

**Comment by tkem** [comment]
Mopidy data models contain the `myaicbrainz_id` field, as documented here: http://mopidy.readthedocs.io/en/latest/api/models/
So no need to try and extract that from the URI, which is an implementation detail and subject to change, anyway.
For local tracks, your files must contain appropriate MBID tags that can be imported when running `mopidy local scan`. This usually means that you have to tag your files using `beets` or Picard`, or some other software that can add MBID tags to your media files. Maybe that's the "obvious" thing missing here ;-)

**Comment by jaedb** [comment]
Ah-hah, that's the missing piece of the puzzle. I mistakenly assumed that `mopidy local scan` fetched and stored the `musicbrainz_id` value. Totally makes sense that it is already stored in the file itself.

PS. Thanks for the quick response!
