### ISSUE TITLE
Show original local file structure in musicbox-webclient

### ISSUE THREAD

**Issue by jemand771** [mopidy/mopidy-local-sqlite#86]
Hello,

recetly, I switched over from using the original json library to sqlite because the search didn't work. Now with sqlite, it works just fine, but I'm not happy with the way the local browser looks now. I just want it to show the directory structure of the local direcory instead of all the fancy other stuff i don't need.

This is what it looks like with the json library (that's what I would like to have)
![unbenannt](https://cloud.githubusercontent.com/assets/19669567/26116591/f7a02732-3a63-11e7-922e-26b449b03e0d.png)

And this is what it looks like (default config)
![unbenannt2](https://cloud.githubusercontent.com/assets/19669567/26116616/0af144b0-3a64-11e7-9ead-2a9467182894.png)

I couldn't really understand how to get back the directory structure. I searched in the internet but found nothing useful.

Additionally, the configuration values for `[local]` and `[local-sqlite]` might be useful:
```[local]
enabled = true
library = sqlite
media_dir = /media/pi/willys/music/
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
  .webm```

```[local-sqlite]
enabled = true
directories =
  Files                   /media/pi/willys/music/
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_album_mbid_uri = true
use_artist_mbid_uri = false
use_artist_sortname = false```

I am using musicbox-webclient with the default configuration values:

```[musicbox_webclient]
enabled = true
musicbox = false
websocket_host =
websocket_port =
on_track_click = PLAY_ALL```

ps: just ignore the other open tabs in the screenshots


Thanks for your time :)

**Comment by tkem** [comment]
This is basically what the [file](https://docs.mopidy.com/en/latest/ext/file/) extension is for: Browsing local files "as-is" without all the "fancy stuff". To avoid duplicated functionality, the "Folders" directory was removed from mopidy-local-sqlite, see #65.
