### ISSUE TITLE
I cant see any artists or albums in MPDroid

### ISSUE THREAD

**Issue by UnconnectedBedna** [mopidy/mopidy-local-sqlite#88]
I installed mopidy-local-sqlite because I thought that would fix the issue of me not being able to browse through artists and albums for my local files. I can play them if I browse into "files" but I want to be able to use the artist and album feature in MPDroid.

I run mopidy as a service and when running "sudo mopidyctl local scan" it finds my files and everything seems to be working but when browsing in artists and albums it's empty.

I have only added 2 mp3:s (to the sd card) to both "local" and "files" to get it to work before adding my mp3 library as a mount. 

What can I do?

**Comment by kingosticks** [comment]
Have you tried with a web client or another MPD client? This sounds a lot like https://github.com/mopidy/mopidy/issues/1314 which should be obvious if you check your log files.

**Comment by UnconnectedBedna** [comment]
I tried to connect with Mopidy android client and I cant even connect with that (but that is not a mopidy-local-sqlite issue).
I'm quite new to this so I'm not sure which logs to look at and running a webclient on the raspberry is not at all what I want, I need an app in my mobile to control the music.
I'm running icecast2 and then opens the stream in vlc or mpc (if that is an issue with this)

**Comment by kingosticks** [comment]
When running as a service you'll find the Mopidy logs in /var/log/mopidy.log.

You can view the webclient page on your phone just like any other Web page. I'm not sure I follow that issue.

**Comment by UnconnectedBedna** [comment]
I got it working by disabling [mpd] and enabling [http] and using "mopidy android app" instead of MPDroid.
I can now browse the local files by artists and albums (I disabled the other ways in the mopidy.config file under [local-sqlite]) via [local].

So in conclusion, I didn't get it to work with MPDroid but found another solution instead.

**Comment by kingosticks** [comment]
There's absolutely no requirement to disable one before enabling the other but it's up to you. There is no local-sqlite bug here.

**Comment by UnconnectedBedna** [comment]
I guess that depends on how you see it, it doesn't work (for me) on the program that mopidy recomends as the best mpd-client (MPDroid)...

**Comment by kingosticks** [comment]
Granted, I will change the documentation to remove the recommendation as the best Android client as it is out of date. The best MPD client in general is still ncmpcpp, followed perhaps by GMPC.

But none of this has anything to do with mopidy-local-sqlite.
