### ISSUE TITLE
Can multiple Mopidy access the same database?

### ISSUE THREAD

**Issue by gerroon** [mopidy/mopidy-local-sqlite#91]
Hi

I am thinking to run multiple Mopidy(on different ports) on the same server which use the same config. I am wondering if this would be a problem for the sqlite backend?

thanks

**Comment by tkem** [comment]
I can't see a major problem, so just go ahead and post your results ;-)
Make sure, of course, that you run `mopidy local scan` only from one instance.

**Comment by gerroon** [comment]
Cool, thanks.
