### ISSUE TITLE
Archive mopidy-local-sqlite once mopidy-local has been released

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-local-sqlite#95]
Blocked by mopidy/mopidy-local#12.

**Comment by jodal** [comment]
I've updated the README with a warning about the extension being unmaintained and replaced by Mopidy-Local. I've also updated the repo description to the pattern we've used for other deprecated/archived repos: "DEPRECATED ({old description})".

@tkem Do you want to review the 5 open issues and 2 pull requests and either close them or transfer them to the Mopidy-Local repo?

When that is done, I'll mark the repo as archived to block any further changes.

**Comment by tkem** [comment]
@jodal: Done.
